name: Go Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Tidy Go modules
        run: go mod tidy
      - name: Run tests
        run: go test ./...
      - name: Run coverage
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
